// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DirectMessages {

  /// <summary>Holder for reflection information generated from message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tZXNzYWdlLnByb3RvEg5EaXJlY3RNZXNzYWdlcyKLAQoHTWVzc2FnZRIW",
            "Cg5tZXNzYWdlQ29udGVudBgBIAEoCRIXCg9tZXNzYWdlRGF0ZVRpbWUYAiAB",
            "KAkSGQoRbWVzc2FnZVNlbmRlck5hbWUYAyABKAkSFwoPbWVzc2FnZUFsaWdt",
            "ZW50GAQgASgJEhsKE21lc3NhZ2VTZW5kZXJTdGF0dXMYBSABKAliBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DirectMessages.Message), global::DirectMessages.Message.Parser, new[]{ "MessageContent", "MessageDateTime", "MessageSenderName", "MessageAligment", "MessageSenderStatus" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DirectMessages.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      messageContent_ = other.messageContent_;
      messageDateTime_ = other.messageDateTime_;
      messageSenderName_ = other.messageSenderName_;
      messageAligment_ = other.messageAligment_;
      messageSenderStatus_ = other.messageSenderStatus_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "messageContent" field.</summary>
    public const int MessageContentFieldNumber = 1;
    private string messageContent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageContent {
      get { return messageContent_; }
      set {
        messageContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "messageDateTime" field.</summary>
    public const int MessageDateTimeFieldNumber = 2;
    private string messageDateTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageDateTime {
      get { return messageDateTime_; }
      set {
        messageDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "messageSenderName" field.</summary>
    public const int MessageSenderNameFieldNumber = 3;
    private string messageSenderName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageSenderName {
      get { return messageSenderName_; }
      set {
        messageSenderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "messageAligment" field.</summary>
    public const int MessageAligmentFieldNumber = 4;
    private string messageAligment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageAligment {
      get { return messageAligment_; }
      set {
        messageAligment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "messageSenderStatus" field.</summary>
    public const int MessageSenderStatusFieldNumber = 5;
    private string messageSenderStatus_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageSenderStatus {
      get { return messageSenderStatus_; }
      set {
        messageSenderStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageContent != other.MessageContent) return false;
      if (MessageDateTime != other.MessageDateTime) return false;
      if (MessageSenderName != other.MessageSenderName) return false;
      if (MessageAligment != other.MessageAligment) return false;
      if (MessageSenderStatus != other.MessageSenderStatus) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageContent.Length != 0) hash ^= MessageContent.GetHashCode();
      if (MessageDateTime.Length != 0) hash ^= MessageDateTime.GetHashCode();
      if (MessageSenderName.Length != 0) hash ^= MessageSenderName.GetHashCode();
      if (MessageAligment.Length != 0) hash ^= MessageAligment.GetHashCode();
      if (MessageSenderStatus.Length != 0) hash ^= MessageSenderStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageContent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageContent);
      }
      if (MessageDateTime.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MessageDateTime);
      }
      if (MessageSenderName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MessageSenderName);
      }
      if (MessageAligment.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MessageAligment);
      }
      if (MessageSenderStatus.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MessageSenderStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageContent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageContent);
      }
      if (MessageDateTime.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MessageDateTime);
      }
      if (MessageSenderName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MessageSenderName);
      }
      if (MessageAligment.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MessageAligment);
      }
      if (MessageSenderStatus.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MessageSenderStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageContent);
      }
      if (MessageDateTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageDateTime);
      }
      if (MessageSenderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageSenderName);
      }
      if (MessageAligment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageAligment);
      }
      if (MessageSenderStatus.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageSenderStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.MessageContent.Length != 0) {
        MessageContent = other.MessageContent;
      }
      if (other.MessageDateTime.Length != 0) {
        MessageDateTime = other.MessageDateTime;
      }
      if (other.MessageSenderName.Length != 0) {
        MessageSenderName = other.MessageSenderName;
      }
      if (other.MessageAligment.Length != 0) {
        MessageAligment = other.MessageAligment;
      }
      if (other.MessageSenderStatus.Length != 0) {
        MessageSenderStatus = other.MessageSenderStatus;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MessageContent = input.ReadString();
            break;
          }
          case 18: {
            MessageDateTime = input.ReadString();
            break;
          }
          case 26: {
            MessageSenderName = input.ReadString();
            break;
          }
          case 34: {
            MessageAligment = input.ReadString();
            break;
          }
          case 42: {
            MessageSenderStatus = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MessageContent = input.ReadString();
            break;
          }
          case 18: {
            MessageDateTime = input.ReadString();
            break;
          }
          case 26: {
            MessageSenderName = input.ReadString();
            break;
          }
          case 34: {
            MessageAligment = input.ReadString();
            break;
          }
          case 42: {
            MessageSenderStatus = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
