USE News
GO

DELETE FROM Posts
DELETE FROM Comments
DELETE FROM Ratings

INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (1, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Game Store Update</h1><h2>Big news in gaming</h2><p>Our game store has just launched a new section for indie titles. Enjoy great discounts and curated lists!</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Click here for a secret discount code</span></p></body></html>', '2025-03-31 10:00:00', 120, 3, 15);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (2, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Exclusive Release</h1><h2>New Game Trailer</h2><p>Check out the trailer for the highly anticipated game release this month. Experience next-level graphics and immersive gameplay.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Spoiler: The main character is unexpected!</span></p></body></html>', '2025-03-31 11:15:00', 85, 2, 8);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (3, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Store Update</h1><h2>New Payment Options</h2><p>We''ve added several new payment methods to make your shopping easier and more secure.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Learn more about our new secure payment gateway</span></p></body></html>', '2025-03-31 12:30:00', 200, 5, 20);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (4, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Special Offer</h1><h2>Limited Time Discount</h2><p>Enjoy a limited time discount on all your favorite games. Hurry, offer ends soon!</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Secret code revealed upon clicking</span></p></body></html>', '2025-03-31 13:45:00', 150, 4, 10);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (5, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Community News</h1><h2>Top Fan Reviews</h2><p>Read what gamers have to say about the latest releases and updates.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Click to view hidden fan ratings</span></p></body></html>', '2025-03-31 14:10:00', 95, 2, 7);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (5, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Developer Update</h1><h2>Patch Notes Released</h2><p>Discover the latest patch notes for improved performance and bug fixes.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">See hidden technical details</span></p></body></html>', '2025-03-31 15:25:00', 210, 8, 18);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (4, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Sales Alert</h1><h2>Weekend Flash Sale</h2><p>Grab your favorite games at unbeatable prices this weekend only.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Reveal extra promo code</span></p></body></html>', '2025-03-31 16:40:00', 175, 6, 9);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (3, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>New Arrivals</h1><h2>Fresh Game Releases</h2><p>Discover the latest additions to our game collection, carefully selected for every type of gamer.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Hidden review snippet</span></p></body></html>', '2025-03-31 18:05:00', 130, 3, 11);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (2, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Tech Insights</h1><h2>Behind the Scenes</h2><p>Learn how our store is using cutting-edge technology to enhance your shopping experience.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">See our tech secret</span></p></body></html>', '2025-03-31 19:20:00', 160, 4, 14);
INSERT INTO Posts (authorId, content, uploadDate, nrLikes, nrDislikes, nrComments) VALUES (1, N'<html><head><style>body{font-family:''Segoe UI'',sans-serif;margin:0;padding:0;color:#333;white-space:pre-wrap;overflow:scroll;}body::-webkit-scrollbar{display:none;}img{display:block;margin:0 auto;max-width:80%;max-height:500px;}h2{margin-top:0;color:#0066cc;font-size:18px;}.spoiler{background-color:black;user-select:none;color:black;cursor:pointer;padding:2px 5px;border-radius:3px;transition:color 0.2s ease-in-out;}.spoiler.revealed{color:white;}</style></head><body><h1>Market Trends</h1><h2>Weekly Analysis</h2><p>Our experts review the latest market trends and share insights into upcoming game releases and technology shifts.</p><p><span class="spoiler" onclick="this.classList.toggle(''revealed'')">Click for a hidden insight</span></p></body></html>', '2025-03-31 20:35:00', 145, 3, 10);
