USE STEAM
GO

DROP TABLE IF EXISTS CHAT_INVITES
DROP TABLE IF EXISTS USERS

CREATE TABLE USERS(
	id INT PRIMARY KEY IDENTITY (1, 1),
	username NVARCHAR(50),
	ipAddress VARCHAR(50),
)

CREATE TABLE CHAT_INVITES(
	sender INT FOREIGN KEY REFERENCES USERS(id),
	receiver INT FOREIGN KEY REFERENCES USERS(id),
)
